---
- name: Patch python3.8 in Ubuntu18.04
  apt:
    upgrade: yes
    update_cache: yes

- name: Install software properties
  apt:
    name: software-properties-common
    state: latest

- name: Install expect
  apt:
    name: expect
    state: latest

- name: Add to Source list
  expect:
    command: add-apt-repository ppa:deadsnakes/ppa
    responses:
      Question:
        - 'Press [ENTER] to continue or Ctrl-c to cancel adding it.': ''

- name: Install Python3.8
  apt:
    name: python3.8
    state: latest

- name: Check Python version
  shell:
    cmd: |
      python3.8 --version
  register: check1

- name: Print check1 result
  debug:
    msg:
      - "{{ check1.stdout }}"

- name: Register env variable
  shell:
    cmd: |
      ln -s /usr/bin/python3 /usr/local/python
  register: register1

- name: Print register1 result
  debug:
    msg:
      - "{{ register1.stdout }}"

- name: Install python3-pip
  apt:
    name: python3-pip
    state: latest

- name: Upgrade latest pip
  shell:
    cmd: |
      python -m pip install --upgrade pip
  register: upgrade1

- name: Print upgrade1 result
  debug:
    msg:
      - "{{ upgrade1.stdout }}"

- name: Install ansible via pip
  pip:
    name: ansible
    executable: pip3

- name: Check ansible version
  shell:
    cmd: |
      ansible --version
  register: check2

- name: Print check2 result
  debug:
    msg:
      - "{{ check2.stdout }}"
