---
- hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: Update and Upgrade
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install Haproxy2.4 PPA
      shell: add-apt-repository ppa:vbernat/haproxy-2.4 -y

    - name: Install Haproxy2.4
      apt:
        name: haproxy
        state: latest

    - name: Check haproxy version
      shell: haproxy -v
      register: check

    - name: Print check
      debug:
        msg:
        - "{{ check.stdout }}"
